# Generated by Django 2.1.7 on 2019-03-04 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Beverages',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('total_pours', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['total_pours'],
                'verbose_name_plural': 'Drinks',
            },
        ),
        migrations.CreateModel(
            name='Pour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Beverage')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venmo', models.CharField(max_length=200)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_drinks', models.IntegerField(default=0)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history', models.ManyToManyField(to='web_interface.Drink')),
            ],
            options={
                'ordering': ['total_drinks'],
                'verbose_name_plural': 'Users',
            },
        ),
    ]
