# Generated by Django 2.1.7 on 2019-03-04 05:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_interface.Drink')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_interface.User'),
        ),
    ]
