# Generated by Django 2.1.7 on 2019-03-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_drink_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='type',
            field=models.CharField(default='liquor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='swipecode',
            field=models.CharField(default='none', max_length=400),
        ),
    ]
