# Generated by Django 2.1.7 on 2019-03-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0004_auto_20190304_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrinkType',
        ),
    ]
