# Generated by Django 2.1.7 on 2019-03-04 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0005_auto_20190303_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
