# Generated by Django 2.1.7 on 2019-03-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0005_delete_drinktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='type',
            field=models.CharField(default='liquor', max_length=200),
            preserve_default=False,
        ),
    ]
