# Generated by Django 2.1.7 on 2019-03-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0008_beverage_drink_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='type',
        ),
    ]
