# Generated by Django 2.1.7 on 2019-03-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0009_remove_beverage_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Orders'},
        ),
    ]
