# Generated by Django 2.1.7 on 2019-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0010_auto_20190305_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
