# Generated by Django 2.1.7 on 2019-03-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0011_beverage_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='picture',
            field=models.CharField(default='react.jpg', max_length=200),
        ),
    ]
