# Generated by Django 2.1.7 on 2019-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_auto_20190303_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='user',
            name='swipecode',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
