# Generated by Django 2.1.7 on 2019-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0006_auto_20190303_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='flowrate',
            field=models.DecimalField(decimal_places=4, default=8.99, max_digits=10),
        ),
        migrations.AddField(
            model_name='beverage',
            name='gpio_pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
