# Generated by Django 2.1.7 on 2019-03-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0007_auto_20190304_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='flowrate',
            field=models.DecimalField(decimal_places=4, default=0.59, max_digits=10),
        ),
    ]
