# Generated by Django 2.1.7 on 2019-03-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0009_auto_20190304_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pour',
            options={'ordering': ['-volume'], 'verbose_name_plural': 'Pours'},
        ),
        migrations.AlterField(
            model_name='drink',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
